version: "3.3"

networks:
  VoiceToText:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/project
      - ./logs:/var/log/nginx
      - ./config/ssls:/etc/nginx/ssls
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
    networks:
      - VoiceToText

  # php
  php-service:
    build: 
      context: .
      dockerfile: ./config/php/Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - VoiceToText