name: "CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3

      - name: Make .env.local
        run: php -r "copy('app/.env', 'app/.env.local');"

      - name: Make .env.test.local
        run: php -r "copy('app/.env.test', 'app/.env.test.local');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: app

      - name: Start PHP server
        run: php -S localhost:8000 -t public &
        working-directory: app

      - name: Execute all tests
        env:
          BASE_URL: http://localhost:8000
        run: vendor/bin/phpunit --testsuite=Unit
        working-directory: app
